version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
      golang: 1.13
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - export GOPATH=${HOME}/go && echo ${GOPATH}
      - export PATH=/usr/local/go/bin:${GOPATH}/bin:${PATH} && echo ${PATH}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker images
      - go get -u "github.com/oranie/cassandra-sample-golang"
      - GOOS=linux GOARCH=amd64  go build ./main.go
      - docker build -t $IMAGE_REPO_NAME .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
